name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Release
        uses: redis-field-engineering/redis-release-version-action@v1
        with:
          version: ${{ github.event.inputs.version }}

      - name: CreateGuide
        run: |
          ./gradlew -Prelease=true -Pfull-release=true \
          createGuide -S

      - name: Release
        uses: redis-field-engineering/redis-release-action@v1
        with:
          gpg-key-id: ${{ secrets.GPG_KEY_ID }}
          gpg-public-key: ${{ secrets.GPG_PUBLIC_KEY }}
          gpg-secret-key: ${{ secrets.GPG_SECRET_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          sonatype-username: ${{ secrets.SONATYPE_USERNAME }}
          sonatype-password: ${{ secrets.SONATYPE_PASSWORD }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          slack-webhook: ${{ secrets.JRELEASER_SLACK_WEBHOOK }}

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/guide/build/docs/asciidoc
